a='Hello'
print(type(a))
a='hello'
#a[0]='c'
a.replace('h','c')
print(a)
v=[]
print(type(v))
v=[4,5,8]
print(v[1])
v=[4,5,8]
v[1]=10
print(v[1])
a='hello'
print(a[0])
print(a[4])
print(a[-4])
a=None
print(type(a))
b=[2,7.9,"hi",None,True]
print(b[0],type(b[0]))
print(b[1],type(b[1]))
print(b[2],type(b[2]))
print(b[3],type(b[3]))
print(b[4],type(b[4]))
